---
- name: Update the Operating System Linux - Working for Redhat and Debian family
  hosts: all
  become: true
  vars:
    reboot_os: false

  tasks:
  - name: Update packages on Debian/Ubuntu
    apt:
      update_cache: yes
      upgrade: full
    when: ansible_os_family == "Debian"
  
  - name: Update packages on Redhat
    dnf:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    
  - name: Reboot the system to apply the upgrade
    reboot:
      msg: "Reboot initiated by Ansible to upgrade the Operating System"
      reboot_timeout: 300
    when: reboot_os
