---
- name: Playbook for user creation
  hosts: localhost
  become: true
  vars_files:
    - vars/secrets.yaml
    - vars/users.yaml
      
 tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ item.user_name }}"
        shell: "{{ item.user_shell }}"
        create_home: "{{ item.home_creation }}"
        groups: "{{ item.user_group if item.user_group != '' else omit }}"
        password: "{{ item.password | password_hash('sha512', 'salt' + item.user_name, rounds=5001) }}"
        update_password: on_create
      loop: "{{ users }}"
