---
- name: Installation of one or more packages on Linux Hosts
  hosts: all
  become: true
  vars_files:
    - vars/packages_install.yaml
  
  tasks:
    - name: Install the package(s) on Debian Family
      apt:
        update_cache: yes
        name: "{{ item.name }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_os_family == "Debian"

    - name: Install the package(s) on Redhat Family
      dnf:
        name: "{{ item.name }}"
        state: latest
      loop: "{{ packages }}"
      when: ansible_os_family == "RedHat"

